/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.api.weather; 

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.client.RestTemplate;
import springfox.documentation.swagger2.annotations.EnableSwagger2;


@SpringBootApplication
@EnableSwagger2
public class Application {


	    public static void main(String[] args) {
	        SpringApplication.run(Application.class, args);
	    }
	    
	    @Bean
		public RestTemplate restTemplate() {
			return new RestTemplate();
		}
	}

